WIDTH = 30                                      # 地图宽
HEIGHT = 30                                     # 地图高
DIST_CENTER_NUM = 5                             # 配送中心数量
DROP_OFF_POINT_NUM = 60                         # 卸货点数量
UAV_MAX_DISTANCE = 20.0                         # 无人机往返极限距离
EXTREME_DISTANCE = UAV_MAX_DISTANCE / 2         # 无人机单程极限距离
UAV_MAX_CARGO_NUM = 10                          # 无人机最大载货量
MIN_REMAIN_TIME = 20                            # 被视为必须完成订单的临时时间
MAX_TASK_NUM = 20                               # 节点单次最大订单数
TIME_INTERVAL = 5                               # 时间步大小（min）
STEP_NUM = int(24 * 60 / TIME_INTERVAL)         # 总时间步数
